### ISSUE TITLE
Does not work for Julia 1.6.0 on Windows

### ISSUE THREAD

**Issue by HerClau** [CoolProp/CoolProp.jl#12]
_
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.0 (2021-03-24)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using Pkg

julia> Pkg.clone("https://github.com/vimalaad/CoolProp.jl.git")
ERROR: UndefVarError: clone not defined
Stacktrace:
 [1] getproperty(x::Module, f::Symbol)
   @ Base .\Base.jl:26
 [2] top-level scope
   @ REPL[2]:1

julia> Pkg.add("https://github.com/vimalaad/CoolProp.jl.git")
ERROR: `https://github.com/vimalaad/CoolProp.jl.git` is not a valid package name
The argument appears to be a URL or path, perhaps you meant `Pkg.add(url="...")` or `Pkg.add(path="...")`.
Stacktrace:
  [1] pkgerror(msg::String)
    @ Pkg.Types C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\Types.jl:55
  [2] check_package_name(x::String, mode::Symbol)
    @ Pkg.API C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\API.jl:56
  [3] #94
    @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\API.jl:149 [inlined]
  [4] foreach
    @ .\abstractarray.jl:2141 [inlined]
  [5] add(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; preserve::Pkg.Types.PreserveLevel, platform::Base.BinaryPlatforms.Platform, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.API C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\API.jl:149
  [6] add
    @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\API.jl:148 [inlined]
  [7] add(pkgs::Vector{Pkg.Types.PackageSpec}; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.API C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\API.jl:73
  [8] add
    @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\API.jl:72 [inlined]
  [9] #add#21
    @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\API.jl:70 [inlined]
 [10] add
    @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\API.jl:70 [inlined]
 [11] #add#20
    @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\API.jl:69 [inlined]
 [12] add(pkg::String)
    @ Pkg.API C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Pkg\src\API.jl:69
 [13] top-level scope
    @ REPL[3]:1

(@v1.6) pkg> add https://github.com/vimalaad/CoolProp.jl.git
     Cloning git-repo `https://github.com/vimalaad/CoolProp.jl.git`
    Updating git-repo `https://github.com/vimalaad/CoolProp.jl.git`
ERROR: could not find project file in package at `https://github.com/vimalaad/CoolProp.jl.git` maybe `subdir` needs to be specified

(@v1.6) pkg> build CoolProp
ERROR: The following package names could not be resolved:
 * CoolProp (not found in project or manifest)

**Comment by NikoBiele** [comment]
I also get that error in Julia 1.6.0 and 1.5.4 but also on 1.5.3 where it used to work. I'm also on Windows 10...

**Comment by NikoBiele** [comment]
Found this, he is also unable to install on 1.6.0, however he did it succesfully on 1.5.4 from existing files :)

https://discourse.julialang.org/t/coolprop-installation-in-julia-1-6-0/58205

**Comment by ibell** [comment]
Seems like a bug in Julia 1.6.0: https://discourse.julialang.org/t/julia-1-6-0-add-package-ohmyrepl/58148/21 (at the bottom)

**Comment by NikoBiele** [comment]
Still does not work in 1.6.1:

   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.1 (2021-04-23)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using Pkg

julia> Pkg.clone("https://github.com/vimalaad/CoolProp.jl.git")
ERROR: UndefVarError: clone not defined
Stacktrace:
 [1] getproperty(x::Module, f::Symbol)
   @ Base .\Base.jl:26
 [2] top-level scope
   @ REPL[2]:1

(@v1.6) pkg> add https://github.com/vimalaad/CoolProp.jl.git
     Cloning git-repo `https://github.com/vimalaad/CoolProp.jl.git`
    Updating git-repo `https://github.com/vimalaad/CoolProp.jl.git`
ERROR: could not find project file in package at `https://github.com/vimalaad/CoolProp.jl.git` maybe `subdir` needs to be specified

________________________________________________________________________________________

However, I made it work on 1.6.1 with an install from my local folder:


  | | |_| | | | (_| |  |  Version 1.6.1 (2021-04-23)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |
(@v1.6) pkg> add C:\Users\jalok\Dropbox\JuliaCoolPropInstall\CoolProp.jl
     Cloning git-repo `C:\Users\jalok\Dropbox\JuliaCoolPropInstall\CoolProp.jl`
    Updating git-repo `C:\Users\jalok\Dropbox\JuliaCoolPropInstall\CoolProp.jl`
    Updating registry at `C:\Users\jalok\.julia\registries\General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Installed Compat ─────────── v3.27.0
   Installed Parsers ────────── v1.1.0
   Installed ConstructionBase ─ v1.1.0
   Installed Unitful ────────── v1.7.0
   Installed JSON ───────────── v0.21.1
    Updating `C:\Users\jalok\.julia\environments\v1.6\Project.toml`
  [e084ae63] + CoolProp v0.0.0 `C:\Users\jalok\Dropbox\JuliaCoolPropInstall\CoolProp.jl#master`
    Updating `C:\Users\jalok\.julia\environments\v1.6\Manifest.toml`
  [34da2185] + Compat v3.27.0
  [187b0558] + ConstructionBase v1.1.0
  [e084ae63] + CoolProp v0.0.0 `C:\Users\jalok\Dropbox\JuliaCoolPropInstall\CoolProp.jl#master`
  [682c06a0] + JSON v0.21.1
  [69de0a69] + Parsers v1.1.0
  [1986cc42] + Unitful v1.7.0
  [8bb1440f] + DelimitedFiles
  [8ba89e20] + Distributed
  [37e2e46d] + LinearAlgebra
  [a63ad114] + Mmap
  [1a1011a3] + SharedArrays
  [2f01184e] + SparseArrays
  [10745b16] + Statistics
  [8dfed614] + Test
    Building CoolProp → `C:\Users\jalok\.julia\scratchspaces\44cfe95a-1eb2-52ea-b672-e2afdf69b78f\0ffe8a45e0437b15241b205c4f8c016cda91e170\build.log`
Precompiling project...
  3 dependencies successfully precompiled in 11 seconds (6 already precompiled)

(@v1.6) pkg> build CoolProp
    Building CoolProp → `C:\Users\jalok\.julia\scratchspaces\44cfe95a-1eb2-52ea-b672-e2afdf69b78f\0ffe8a45e0437b15241b205c4f8c016cda91e170\build.log`

julia> using CoolProp

julia> PropsSI("T","P",101325,"Q",0,"WATER")
373.1242958476844

So I don't think this is an issue with Julia? But I admit my knowledge is very limited. :)

**Comment by cstook** [comment]
Looks like you are installing from the wrong repo.  See https://github.com/CoolProp/CoolProp.jl/issues/10#issuecomment-579011851

**Comment by NikoBiele** [comment]
Thanks :) I just followed the readme... Maybe the readme should be updated then?

**Comment by cstook** [comment]
There is already a pull request.  https://github.com/CoolProp/CoolProp.jl/pull/9.  I don't know who need to process this.
