### ISSUE TITLE
Tag a release?

### ISSUE THREAD

**Issue by barche** [CoolProp/CoolProp.jl#13]
Hi, it would be nice if this package could get a release in the Julia general registry, that way it will work nicely with the new Pluto notebook integrated package manager.

**Comment by duncanam** [comment]
@barche and/or @ibell do you know who administers this project? It would be great if some of us could take some stabs at updating this. Currently this package is the easiest way to interface with both CoolProp and REFPROP, and having it both maintained (I can try and assist here) and integrated into Julia's package manager would be superb. I had a PR #9 open to fix for quite a while on the original package that was never merged, until it looks like it was corrected for latest release with #14 which is open now.

**Comment by barche** [comment]
@jowr is listed as org admin for CoolProp, I'd also be willing to help out maintaining the Julia wrappers, I use this package in class and having an updated release in the Julia package registry would be a big help to simplify installation for our students.

**Comment by ibell** [comment]
I can add you as an administrator.  Where we really need help is overall
management of the project.   There are currently no full-time devs

**Comment by barche** [comment]
Sure, I would appreciate it. I have a vested interest in at least keeping CoolProp.jl going, if needed I can help out with compilation fixes and so on if things break in the upstream library. But I have no expertise in the science behind the library, I'm just a user.

**Comment by ederag** [comment]
A kind ping, to @ibell or @jowr maybe ?
It would be good to give @barche access rights, so that #14 could be merged,
and this package registered ?

**Comment by ibell** [comment]
Sorry this took so long...

**Comment by barche** [comment]
No problem, thanks, I'll look into doing a release.

**Comment by barche** [comment]
@JuliaRegistrator register

**Comment by barche** [comment]
@JuliaRegistrator register

**Comment by barche** [comment]
CoolProp.jl is now in the registry and installable using just `add CoolProp`. Thanks for the help @ibell !

**Comment by duncanam** [comment]
Thanks for doing this! This is excellent.

Mar 3, 2022 12:09:18 AM Bart Janssens ***@***.***>:
